spring.application.name=doctor-service

spring.datasource.url=jdbc:mysql://localhost:3306/doctor_db
spring.datasource.username=root
spring.datasource.password=nitin

spring.jpa.hibernate.ddl-auto=update

server.port=8081
